Document: gpg-body
Title: Debian gpg-body Manual
Author: <insert document author here>
Abstract: This manual describes what gpg-body is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gpg-body/gpg-body.sgml.gz

Format: postscript
Files: /usr/share/doc/gpg-body/gpg-body.ps.gz

Format: text
Files: /usr/share/doc/gpg-body/gpg-body.text.gz

Format: HTML
Index: /usr/share/doc/gpg-body/html/index.html
Files: /usr/share/doc/gpg-body/html/*.html
